server:
  port: 8108
spring:
  application:
    name: zipkin-service2
  zipkin:
    base-url: http://localhost:9411
    service:
      name: ${spring.application.name}
  cloud:
    zookeeper:
      connect-string: localhost:2181
