spring:
  application:
    name: springcloudconfigserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lumiseven/skt
          default-label: master #配置文件分支
          search-paths:
            - configcenter/springcloudconfig/src/main/resources/config/{application}
            - configcenter/springcloudconfig/src/main/resources/config/default
          clone-on-start: true
server:
  port: 8060