server:
  port: 8080
spring:
  application:
    name: consul-producer
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        register: true

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
