server:
  port: 8107
spring:
  application:
    name: zipkin-service1
  zipkin:
    base-url: http://localhost:9411
    service:
      name: ${spring.application.name}
  cloud:
    zookeeper:
      connect-string: localhost:2181
