server:
  port: 8061
spring:
  application:
    name: springcloudconfigclient
  config:
    import: configserver:http://localhost:8060
  cloud:
    config:
      label: master
      fail-fast: true
#  cloud:
#    config:
#      label: master
#      uri: http://localhost:8060
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,env

