server:
  port: 8089
spring:
  application:
    name: consumer-provider
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        register: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo2?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: admin
mybatis:
  mapper-locations: classpath:mapper/*.xml
seata:
  tx-service-group: seata-consumer-group
