{
 "title": "hippo4j",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application_name", "query": { "query": "label_values(application_name)" } },
   {
    "name": "dynamic_thread_pool_id",
    "query": {
     "query": "label_values(dynamic_thread_pool_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Load Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "当前负载",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dynamic_thread_pool_current_load{application_name=\"$application_name\",dynamic_thread_pool_id=\"$dynamic_thread_pool_id\",}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "峰值负载",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dynamic_thread_pool_peak_load{application_name=\"$application_name\",dynamic_thread_pool_id=\"$dynamic_thread_pool_id\",}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "核心线程数",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dynamic_thread_pool_core_size{application_name=\"$application_name\",dynamic_thread_pool_id=\"$dynamic_thread_pool_id\",}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "最大线程数",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dynamic_thread_pool_maximum_size{application_name=\"$application_name\",dynamic_thread_pool_id=\"$dynamic_thread_pool_id\",}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Core Param", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "当前线程数",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dynamic_thread_pool_current_size{application_name=\"$application_name\",dynamic_thread_pool_id=\"$dynamic_thread_pool_id\",}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "活跃线程数",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dynamic_thread_pool_active_size{application_name=\"$application_name\",dynamic_thread_pool_id=\"$dynamic_thread_pool_id\",}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "任务完成数",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dynamic_thread_pool_completed_task_count{application_name=\"$application_name\",dynamic_thread_pool_id=\"$dynamic_thread_pool_id\",}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "队列中任务数量",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dynamic_thread_pool_queue_size{application_name=\"$application_name\",dynamic_thread_pool_id=\"$dynamic_thread_pool_id\",}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "队列剩余容量",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "dynamic_thread_pool_queue_remaining_capacity{application_name=\"$application_name\",dynamic_thread_pool_id=\"$dynamic_thread_pool_id\",}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "拒绝策略",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dynamic_thread_pool_reject_count{application_name=\"$application_name\",dynamic_thread_pool_id=\"$dynamic_thread_pool_id\",}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}